image: jelaniwoods/appdev2021-vanilla-rails@sha256:478d74c7a640c152f428a9801c484ae19c780745fc6cd61ad28cd5448a4997b

tasks:
  - command: bundle install
  - init: bin/setup
ports:
  - port: 3000
    onOpen: open-preview
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - shd101wyy.markdown-preview-enhanced
    - wingrunr21.vscode-ruby
    - mbessey.vscode-rufo
    - aliariff.vscode-erb-beautify
